services:
  stats-server:
    build: ./stats-server/stats-service
    container_name: stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat


  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats

  ewm-service:
    build: ./ewm-service
    ports:
      - "8080:8080"
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-service-db
    ports:
      - "7542:5432"
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=ewm-main